// <auto-generated />
using System;
using CoachBoard.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachBoard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoachBoardDbContext))]
    partial class CoachBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoachBoard.Core.Entities.Assist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssistFixtureId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PlayerAssistedId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssistFixtureId");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.HasIndex("PlayerAssistedId");

                    b.ToTable("Assists");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Career", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Fixture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Competition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("OpponentGoals")
                        .HasColumnType("int");

                    b.Property<long>("OpponentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("TeamId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssistId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwnGoal")
                        .HasColumnType("bit");

                    b.Property<long?>("PlayerScoredId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PlayerScoredId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Opponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CareerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerId");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KitNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CareerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ContractYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PlayerTransferredId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Salary")
                        .HasPrecision(14, 8)
                        .HasColumnType("decimal(14,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTransferredId");

                    b.HasIndex("TeamId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FixturePlayer", b =>
                {
                    b.Property<long>("FixturesId")
                        .HasColumnType("bigint");

                    b.Property<long>("LineUpId")
                        .HasColumnType("bigint");

                    b.HasKey("FixturesId", "LineUpId");

                    b.HasIndex("LineUpId");

                    b.ToTable("FixturePlayer");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Assist", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Fixture", "Fixture")
                        .WithMany("Assists")
                        .HasForeignKey("AssistFixtureId")
                        .IsRequired();

                    b.HasOne("CoachBoard.Core.Entities.Goal", "Goal")
                        .WithOne("Assist")
                        .HasForeignKey("CoachBoard.Core.Entities.Assist", "GoalId");

                    b.HasOne("CoachBoard.Core.Entities.Player", "PlayerAssisted")
                        .WithMany("Assists")
                        .HasForeignKey("PlayerAssistedId");

                    b.Navigation("Fixture");

                    b.Navigation("Goal");

                    b.Navigation("PlayerAssisted");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Career", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.User", "User")
                        .WithMany("Careers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Fixture", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Opponent", "Opponent")
                        .WithMany("Fixtures")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachBoard.Core.Entities.Team", "Team")
                        .WithMany("Fixtures")
                        .HasForeignKey("TeamId")
                        .IsRequired();

                    b.Navigation("Opponent");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Goal", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Fixture", "Fixture")
                        .WithMany("Goals")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachBoard.Core.Entities.Player", "PlayerScored")
                        .WithMany("Goals")
                        .HasForeignKey("PlayerScoredId");

                    b.Navigation("Fixture");

                    b.Navigation("PlayerScored");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Opponent", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Career", "Career")
                        .WithMany("Opponents")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Player", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Team", "Team")
                        .WithMany("Squad")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Team", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Career", "Career")
                        .WithMany("Teams")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Transfer", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Player", "PlayerTransferred")
                        .WithMany("Transfers")
                        .HasForeignKey("PlayerTransferredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachBoard.Core.Entities.Team", "Team")
                        .WithMany("Transfers")
                        .HasForeignKey("TeamId")
                        .IsRequired();

                    b.Navigation("PlayerTransferred");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FixturePlayer", b =>
                {
                    b.HasOne("CoachBoard.Core.Entities.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixturesId")
                        .IsRequired();

                    b.HasOne("CoachBoard.Core.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("LineUpId")
                        .IsRequired();
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Career", b =>
                {
                    b.Navigation("Opponents");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Fixture", b =>
                {
                    b.Navigation("Assists");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Goal", b =>
                {
                    b.Navigation("Assist");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Opponent", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Player", b =>
                {
                    b.Navigation("Assists");

                    b.Navigation("Goals");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.Team", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Squad");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("CoachBoard.Core.Entities.User", b =>
                {
                    b.Navigation("Careers");
                });
#pragma warning restore 612, 618
        }
    }
}
